name: video_cached_player
description: A new flutter plugin that is virtually a clone of official video_player plugin except that it supports caching( Android and iOS)
version: 2.4.9+1
homepage: https://github.com/JungJongSeok/flutter_cached_video_player

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.loco.cached_video_player
        pluginClass: CachedVideoPlayerPlugin
      ios:
        pluginClass: CachedVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: ^1.15.0
  flutter:
    sdk: flutter
  html: ^0.15.4
  video_player: ^2.9.1
  video_player_android: ^2.7.3
  video_player_avfoundation: ^2.6.1
  video_player_platform_interface: ^6.2.2
  plugin_platform_interface: ^2.1.8
  video_player_web: ^2.0.0

dev_dependencies:
  lints: ^2.0.1
  pedantic: ^1.11.1
  pigeon: ^3.1.0
